#!/bin/sh
# Environment
set -eu

unset TMPDIR

TEST_PASS=0
TEST_FAIL=0
TEST_IGNORED=0

IGNORE_LIST=""

# FIXME: This should be done in default adt environment
# Detect the ubuntu-ci setup
if getent hosts squid.internal >/dev/null 2>&1; then
    echo "Running in the Canonical CI environment"
    export http_proxy="http://squid.internal:3128"
    export https_proxy="http://squid.internal:3128"
fi

# Helper functions
pass() {
    TEST_PASS=$((${TEST_PASS}+1))
    echo "PASS: $1"
}

fail() {
    for entry in $IGNORE_LIST; do
        if [ "$entry" = "$2" ]; then
            ignore $1
            return
        fi
    done

    TEST_FAIL=$((${TEST_FAIL}+1))
    echo "FAIL: $1"

    if [ -f "$3" ]; then
        echo "---"
        cat $3
        echo "---"
    fi
}

ignore() {
    TEST_IGNORED=$((${TEST_IGNORED}+1))
    echo "IGNORED: $*"
}

summary() {
    echo ""
    echo "SUMMARY: pass=$TEST_PASS, fail=$TEST_FAIL, ignored=$TEST_IGNORED"
}

# The actual tests
## Default testsuite
for testbin in /usr/bin/lxc-test-*; do
    STRING="lxc-tests: $testbin"
    [ ! -x "$testbin" ] && continue

    # Some tests can't be run standalone
    [ "$testbin" = "/usr/bin/lxc-test-may-control" ] && continue

    OUT=$(mktemp)
    $testbin >$OUT 2>&1 && pass "$STRING" || fail "$STRING" "$testbin" "$OUT"
    rm $OUT
done

## Python3 testsuite
OUT=$(mktemp)

STRING="python3: API"
PYTEST=$(mktemp)
cat /usr/share/doc/python3-lxc/examples/api_test.py.gz | gzip -d > $PYTEST
python3 $PYTEST >$OUT 2>&1 && pass "$STRING" || fail "$STRING" "python3" "$OUT"
rm $PYTEST

rm $OUT

# Test summary
summary

[ "$TEST_FAIL" != "0" ] && exit 1

exit 0
